### ISSUE TITLE
how do I run this?

### ISSUE THREAD

**Issue by shaunlebron** [asolove/restate#1]
hi I was enjoying your article on pure ui control, and couldn't figure out how to run this.

```
npm start

...

File "/Users/swilliam/code/restate/motivation/naive/view.re", line 26, characters 19-37:
Error: This pattern matches values of type Updater.t
       but a pattern was expected which matches values of type
         ('a, 'b) ReasonReact.self
```

**Comment by asolove** [comment]
Thanks for reporting! It looks like reason-react v0.2.x made some changes and this project only works with v0.1.x. I'm pushing a fix to the package.json to be more specific about that, and I'll upgrade to 0.2.x with the next set of changes in here.
